CREATE TABLE IF NOT EXISTS `ly_order` (
  `id` BIGINT NOT NULL COMMENT '订单ID',
  `order_no` VARCHAR(64) NOT NULL COMMENT '订单号',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `order_type` TINYINT NOT NULL DEFAULT 0 COMMENT '订单类型:0普通,1秒杀',
  `status` TINYINT NOT NULL COMMENT '订单状态:10待支付,20已支付,30已发货,40已完成,50已取消',
  `pay_status` TINYINT NOT NULL DEFAULT 0 COMMENT '支付状态:0未支付,1已支付,2已退款',
  `total_amount` DECIMAL(12,2) NOT NULL COMMENT '订单总金额',
  `pay_amount` DECIMAL(12,2) NOT NULL COMMENT '实付金额',
  `receiver_name` VARCHAR(64) DEFAULT NULL COMMENT '收货人姓名',
  `receiver_phone` VARCHAR(20) DEFAULT NULL COMMENT '收货人电话',
  `receiver_address` VARCHAR(255) DEFAULT NULL COMMENT '收货地址',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '订单备注',
  `paid_at` DATETIME DEFAULT NULL COMMENT '支付时间',
  `cancelled_at` DATETIME DEFAULT NULL COMMENT '取消时间',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除:0否,1是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ly_order_no` (`order_no`),
  KEY `idx_ly_order_user_status_ct` (`user_id`,`status`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单主表';
