CREATE TABLE IF NOT EXISTS `ly_activity_sku` (
  `id` BIGINT NOT NULL COMMENT '活动商品ID',
  `activity_id` BIGINT NOT NULL COMMENT '活动ID',
  `sku_id` BIGINT NOT NULL COMMENT 'SKU ID',
  `seckill_price` DECIMAL(10,2) NOT NULL COMMENT '秒杀价格',
  `stock_total` INT NOT NULL COMMENT '总库存',
  `stock_available` INT NOT NULL COMMENT '可用库存',
  `stock_locked` INT NOT NULL DEFAULT 0 COMMENT '锁定库存',
  `limit_per_user` INT NOT NULL DEFAULT 1 COMMENT '单用户限购数',
  `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态:1启用,0禁用',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除:0否,1是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ly_activity_sku` (`activity_id`,`sku_id`),
  KEY `idx_ly_activity_sku_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='秒杀活动商品表';
