CREATE TABLE IF NOT EXISTS `ly_permission` (
  `id` BIGINT NOT NULL COMMENT '权限ID',
  `perm_code` VARCHAR(128) NOT NULL COMMENT '权限编码',
  `perm_name` VARCHAR(128) NOT NULL COMMENT '权限名称',
  `perm_type` VARCHAR(16) NOT NULL DEFAULT 'API' COMMENT '权限类型:MENU/BUTTON/API',
  `path` VARCHAR(255) DEFAULT NULL COMMENT '资源路径',
  `method` VARCHAR(16) DEFAULT NULL COMMENT 'HTTP方法',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态:1启用,0禁用',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除:0否,1是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ly_permission_code` (`perm_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='权限资源表';
