CREATE TABLE IF NOT EXISTS `ly_kb_file` (
  `id` BIGINT NOT NULL COMMENT '文件ID',
  `kb_id` BIGINT NOT NULL COMMENT '知识库ID',
  `file_name` VARCHAR(255) NOT NULL COMMENT '文件名称',
  `file_url` VARCHAR(512) NOT NULL COMMENT '文件存储地址',
  `file_type` VARCHAR(32) DEFAULT NULL COMMENT '文件类型',
  `file_size` BIGINT DEFAULT NULL COMMENT '文件大小(字节)',
  `parse_status` TINYINT NOT NULL DEFAULT 0 COMMENT '解析状态:0待解析,1成功,2失败',
  `parse_error` VARCHAR(255) DEFAULT NULL COMMENT '解析错误信息',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除:0否,1是',
  PRIMARY KEY (`id`),
  KEY `idx_ly_kb_file_kb` (`kb_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='知识库文件表';
