spring:
  application:
    name: lingyi-user
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml?refreshEnabled=false
      - optional:nacos:common-${spring.profiles.active}.yaml?refreshEnabled=false
  nacos:
    config:
      server-addr: ${NACOS_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      namespace: ${NACOS_NAMESPACE:${NACOS_NAMESPACE_DEV:27119826-e1e3-481e-a1db-25eddb7f2327}}
      timeout: ${NACOS_CONFIG_TIMEOUT:10000}
      refresh-enabled: ${NACOS_CONFIG_REFRESH_ENABLED:false}
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        namespace: ${NACOS_NAMESPACE:${NACOS_NAMESPACE_DEV:27119826-e1e3-481e-a1db-25eddb7f2327}}
      config:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        namespace: ${NACOS_NAMESPACE:${NACOS_NAMESPACE_DEV:27119826-e1e3-481e-a1db-25eddb7f2327}}
        timeout: ${NACOS_CONFIG_TIMEOUT:10000}
        refresh-enabled: ${NACOS_CONFIG_REFRESH_ENABLED:false}
