apiVersion: apps/v1
kind: Deployment
metadata:
  name: lingyi-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lingyi-user
  template:
    metadata:
      labels:
        app: lingyi-user
    spec:
      containers:
        - name: user
          image: lingyi/user:latest
          ports:
            - containerPort: 18081

